Repository opensearch-project/data-prepper, pull requests merged in 2022-10, with the labels that each got.

#1899 Adds a stack-trace to failures from OpenSearch
  data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
Labels: backport 2.0

#1901 Added change log for 2.0.0
  release/release-notes/data-prepper.change-log-2.0.0.md
Labels: backport 2.0

#1894 Conditional routing documentation
  docs/overview.md
Labels: backport 2.0

#1906 Increase the default buffer configurations by 25
  data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java
Labels: backport 2.0

#1909 Updated the change log for 2.0.0
  release/release-notes/data-prepper.change-log-2.0.0.md
Labels: backport 2.0

#1910 Simple duration regex did not allow for 0s or 0ms
  data-prepper-core/src/main/java/org/opensearch/dataprepper/parser/DataPrepperDurationDeserializer.java
  data-prepper-core/src/test/java/org/opensearch/dataprepper/parser/DataPrepperDurationDeserializerTest.java
Labels: backport 2.0

#1897 Fix PipelineConnector to duplicate the events
  .github/workflows/data-prepper-log-analytics-basic-grok-e2e-tests.yml
  data-prepper-api/src/main/java/org/opensearch/dataprepper/model/trace/JacksonSpan.java
  data-prepper-api/src/test/java/org/opensearch/dataprepper/model/trace/JacksonSpanTest.java
  data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java
  data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineConnectorTest.java
  e2e-test/log/build.gradle
  e2e-test/log/src/integrationTest/java/org/opensearch/dataprepper/integration/log/ParallelGrokStringSubstituteLogTest.java
  e2e-test/log/src/integrationTest/resources/parallel-grok-substitute-e2e-pipeline.yml
Labels: backport 2.0

#1925 Jackson 2.13.4.2
  build.gradle
Labels: backport 1.5, backport 2.0

#1926 Bug Fix: S3 source key
  data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/SqsWorkerIT.java
  data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
  data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java
Labels: backport 2.0

#1938 Require protobuf-java-util 3.21.7 to fix #1891
  build.gradle
Labels: backport 1.x, backport 1.5, backport 2.0

#1939 Delete s3:TestEvent objects and log them
  data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
  data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java
Labels: backport 2.0

#1954 Use Python grpcio 1.50.0 in smoke tests to reduce time to run.
  release/smoke-tests/otel-span-exporter/requirements.txt
Labels: backport 1.x, backport 1.5, backport 2.0

#1955 Run smoke tests against OpenSearch 1.3.6.
  release/smoke-tests/run-smoke-tests.sh
Labels: backport 1.x, backport 1.5, backport 2.0

#1921 Attempt to reduce flakiness in RandomStringSourceTests
  data-prepper-plugins/common/src/test/java/org/opensearch/dataprepper/plugins/source/RandomStringSourceTests.java
Labels: backport 1.x, backport 1.5, backport 2.0

#1956 Reduce smoke test timeout to 8 minutes from 30 minutes
  .github/workflows/release.yml
Labels: backport 2.0

#1976 Added release notes for 1.5.2
  release/release-notes/data-prepper.release-notes-1.5.2.md
Labels: backport 1.5

#1969 Created release notes for Data Prepper 2.0.1
  release/release-notes/data-prepper.release-notes-2.0.1.md
Labels: backport 2.0

#1981 Updated release notes and change log with spring change
  release/release-notes/data-prepper.change-log-1.5.2.md
  release/release-notes/data-prepper.release-notes-1.5.2.md
Labels: backport 1.5
