Repository opensearch-project/data-prepper, pull requests merged in 2022-06, with the labels that each got.

#1466 Add health check to HTTP source
  data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSource.java
  data-prepper-plugins/http-source/src/main/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceConfig.java
  data-prepper-plugins/http-source/src/test/java/com/amazon/dataprepper/plugins/source/loghttp/HTTPSourceTest.java
Labels: backport 1.4

#1535 Added the auto-generated CHANGELOG for Data Prepper 1.5.0
  release/release-notes/data-prepper.change-log-1.5.0.md
Labels: backport 1.x, backport 1.5

#1538 Fixes a bug in the SqsWorkerIT where an NPE occurs and README.md update
  data-prepper-plugins/s3-source/README.md
  data-prepper-plugins/s3-source/src/integrationTest/java/com/amazon/dataprepper/plugins/source/SqsWorkerIT.java
Labels: backport 1.x, backport 1.5

#1547 Enable HTTP Health Check for OTelTraceSource and OTelMetricsSource.
  data-prepper-plugins/otel-metrics-source/README.md
  data-prepper-plugins/otel-metrics-source/src/main/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSource.java
  data-prepper-plugins/otel-metrics-source/src/main/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceConfig.java
  data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java
  data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OtelMetricsSourceConfigTests.java
  data-prepper-plugins/otel-trace-source/README.md
  data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSource.java
  data-prepper-plugins/otel-trace-source/src/main/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceConfig.java
  data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OTelTraceSourceTest.java
  data-prepper-plugins/otel-trace-source/src/test/java/com/amazon/dataprepper/plugins/source/oteltrace/OtelTraceSourceConfigTests.java
Labels: backport 1.x
