Repository opensearch-project/data-prepper, pull requests merged in 2023-05, with the labels that each got.

#2569 Consolidates use of OpenSearch clients and some related clean-up
  data-prepper-plugins/opensearch/build.gradle
  data-prepper-plugins/otel-trace-group-processor/build.gradle
  settings.gradle
Labels: maintenance, backport 2.2

#2605 Log clear messages when OpenSearch Sink fails to push. Modify retries to be iterative instead of recursive
  data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
  data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
Labels: backport 2.2

#2634 Updates the example Spring Boot application to Spring Boot 2.7.11
  examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle
Labels: backport 2.2

#2635 Update to use Jetty 11.0.14 in the s3-source project to fix
  data-prepper-plugins/s3-source/build.gradle
Labels: backport 2.2

#2643 Fix OpenSearch Retry mechanism
  data-prepper-plugins/opensearch/build.gradle
  data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BackOffUtils.java
  data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
  data-prepper-plugins/opensearch/src/test/java/org/opensearch/dataprepper/plugins/sink/opensearch/BackOffUtilsTests.java
Labels: backport 2.2

#2651 Update to Snakeyaml 2.0 in the Trace Analytics sample app.
  examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle
Labels: backport 2.2

#2660 Added 2.2.1 change log
  release/release-notes/data-prepper.change-log-2.2.1.md
Labels: backport 2.2

#2664 Added 2.2.1 release notes
  release/release-notes/data-prepper.release-notes-2.2.1.md
Labels: backport 2.2

#2678 addressing copy and paste error
  data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java
Labels: backport 2.2

#2701 Add backoff when flushing on add and change condition to >=
  data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/BufferAccumulator.java
  data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/BufferAccumulatorTest.java
Labels: backport 2.2

#2728 Use the same Log4j configuration for integration tests as used for unit testing
  data-prepper-core/build.gradle
Labels: maintenance

#2742 Removes JUnit Vintage from the root project
  data-prepper-api/build.gradle
  data-prepper-core/build.gradle
  data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/GrammarLexerTest.java
  data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/DateLogstashPluginAttributesMapperTest.java
  data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/LogstashMapperTest.java
  data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/mapping/LogstashPluginMapperTest.java
  data-prepper-logstash-configuration/src/test/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitorTest.java
  data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateActionConfigTests.java
  data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateActionConfigTests.java
  data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorConfigTests.java
  data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/AnomalyDetectorProcessorTests.java
  data-prepper-plugins/anomaly-detector-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/anomalydetector/modes/RandomCutForestModeConfigTests.java
  data-prepper-plugins/armeria-common/src/test/java/org/opensearch/dataprepper/compression/CompressionOptionTest.java
  data-prepper-plugins/avro-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/avro/AvroInputCodecTest.java
  data-prepper-plugins/blocking-buffer/src/test/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBufferTests.java
  data-prepper-plugins/common/build.gradle
  data-prepper-plugins/grok-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessorConfigTests.java
  data-prepper-plugins/http-source/src/test/java/org/opensearch/dataprepper/plugins/source/loghttp/HTTPSourceConfigTest.java
  data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/KafkaSourceConfigTest.java
  data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/SchemaConfigTest.java
  data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/configuration/TopicsConfigTest.java
  data-prepper-plugins/log-generator-source/src/test/java/org/opensearch/dataprepper/plugins/source/loggenerator/LogGeneratorSourceTest.java
  data-prepper-plugins/mapdb-processor-state/build.gradle
  data-prepper-plugins/opensearch/build.gradle
  data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/health/HealthGrpcServiceTest.java
  data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/source/otellogs/OTelLogsSourceTest.java
  data-prepper-plugins/otel-logs-source/src/test/java/org/opensearch/dataprepper/plugins/source/otellogs/OtelLogsSourceConfigTests.java
  data-prepper-plugins/otel-metrics-raw-processor/build.gradle
  data-prepper-plugins/otel-metrics-source/build.gradle
  data-prepper-plugins/otel-trace-group-processor/build.gradle
  data-prepper-plugins/otel-trace-raw-processor/build.gradle
  data-prepper-plugins/otel-trace-source/build.gradle
  data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/S3SinkConfigTest.java
  data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/sink/S3SinkTest.java
  data-prepper-plugins/s3-source/build.gradle
  data-prepper-plugins/service-map-stateful/src/test/java/org/opensearch/dataprepper/plugins/processor/ServiceMapStatefulProcessorTest.java
  e2e-test/build.gradle
  settings.gradle
Labels: maintenance
