Repository opensearch-project/data-prepper, pull requests merged in 2023-09, with the labels that each got.

#3269 Updates to Gradle 8.3; fixes deprecated Gradle behavior
  data-prepper-main/build.gradle
  e2e-test/build.gradle
  e2e-test/log/build.gradle
  e2e-test/peerforwarder/build.gradle
  e2e-test/trace/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  performance-test/build.gradle
  release/archives/build.gradle
  release/docker/build.gradle
Labels: backport 2.4

#3317 Fix NPE in s3 scan partition supplier
  data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java
  data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplierTest.java
Labels: backport 2.4

#3331 BUG: Stop S3 source on InterruptedException
  data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanService.java
  data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/ScanObjectWorker.java
  data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsService.java
  data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java
Labels: backport 2.4

#3343 Updates trace analytics sample app dependencies
  examples/trace-analytics-sample-app/sample-app/Dockerfile
  examples/trace-analytics-sample-app/sample-app/analytics-service/Dockerfile
  examples/trace-analytics-sample-app/sample-app/analytics-service/README.md
  examples/trace-analytics-sample-app/sample-app/analytics-service/build.gradle
Labels: backport 2.4

#3348 Updates Trace Analytics sample appliction to run again
  .github/workflows/examples-trace-analytics.yml
  examples/trace-analytics-sample-app/sample-app/Dockerfile
  examples/trace-analytics-sample-app/sample-app/analytics-service/Dockerfile
  examples/trace-analytics-sample-app/sample-app/authenticationService.py
  examples/trace-analytics-sample-app/sample-app/client.py
  examples/trace-analytics-sample-app/sample-app/paymentService.py
  examples/trace-analytics-sample-app/sample-app/recommendationService.py
  examples/trace-analytics-sample-app/sample-app/requirements.txt
  examples/trace-analytics-sample-app/sample-app/script.sh
Labels: backport 2.4

#3351 Armeria 1.25.2
  build.gradle
  data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/PeerForwarder_ClientServerIT.java
  settings.gradle
Labels: backport 2.4

#3364 Fix exemplar list in Histogram and Count aggregations
  data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/CountAggregateAction.java
  data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/HistogramAggregateAction.java
Labels: backport 2.4

#3371 Fixes CVE-2023-42503 by updating commons-compress
  data-prepper-api/build.gradle
  data-prepper-plugins/common/build.gradle
  data-prepper-plugins/geoip-processor/build.gradle
  data-prepper-plugins/http-sink/build.gradle
  data-prepper-plugins/http-source/build.gradle
  data-prepper-plugins/opensearch/build.gradle
  data-prepper-plugins/otel-logs-source/build.gradle
  data-prepper-plugins/otel-metrics-raw-processor/build.gradle
  data-prepper-plugins/otel-metrics-source/build.gradle
  data-prepper-plugins/otel-proto-common/build.gradle
  data-prepper-plugins/otel-trace-raw-processor/build.gradle
  data-prepper-plugins/otel-trace-source/build.gradle
  data-prepper-plugins/prometheus-sink/build.gradle
  data-prepper-plugins/s3-sink/build.gradle
  data-prepper-plugins/s3-source/build.gradle
  data-prepper-plugins/service-map-stateful/build.gradle
  settings.gradle
Labels: backport 2.4

#3385 CVE fixes
  build.gradle
  data-prepper-plugins/parquet-codecs/build.gradle
  data-prepper-plugins/s3-sink/build.gradle
  data-prepper-plugins/s3-source/build.gradle
  settings.gradle
Labels: backport 2.4

#3387 Improve logging for failed documents in the OpenSearch sink
  data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java
Labels: backport 2.4

#3397 2.4.1 change log
  release/release-notes/data-prepper.change-log-2.4.1.md
Labels: backport 2.4

#3398 2.4.1 release notes
  release/release-notes/data-prepper-release-notes-2.4.1.md
Labels: backport 2.4

#3399 Add retry to Kafka Consumer Create in source
  data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java
  data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSourceTest.java
Labels: backport 2.5

#3403 Updated release notes file name
  release/release-notes/data-prepper.release-notes-2.4.1.md
Labels: backport 2.4, backport 2.5

#3404 Fix CVE-2022-45688, CVE-2023-43642
  build.gradle
Labels: backport 2.4, backport 2.5
